name: Initiative Request - Automatic PR

on:
  issues:
    types: [opened, edited]

jobs:
  create-pr:
    if: contains(github.event.issue.labels.*.name, 'new-initiative-request')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "$GITHUB_WORKSPACE/scripts/requirements.txt"

      - name: Run GPT script
        uses: nick-fields/retry@v2
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: python $GITHUB_WORKSPACE/scripts/gptGenerateJsonFromIssue.py
          
      - name: Generate PR
        uses: actions/github-script@v6
        env:
          ISSUE_AUTHOR: ${{ github.event.issue.user.name }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        with:
          script: |
            const script = require(process.env.GITHUB_WORKSPACE + '/scripts/generatePullRequestForNewInitiative.js')
            await script({github, context})
