name: Monitor initiative Link Availbility

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 1 * * *'

defaults:
  run:
    working-directory: ./scripts/link-availability

jobs:
  monitor-availability:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm ci
    - run: npm start
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_AVAILABILITY_ISSUE_NUMBER: ${{ vars.AVAILABILITY_MONITOR_ISSUE_NUMBER }}
        MAX_CONCURRENCY_LEVEL: 100
