name: PR Deployment

on: [pull_request, workflow_dispatch]

jobs:
  deploy:
    permissions: 
      contents: read
      pull-requests: write

    uses: ./.github/workflows/reusable-deploy-vercel.yml
    
    with:
      PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
    
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}