name: Preview Deployment

on: 
  workflow_dispatch:
    inputs:
      REF:
        type: string
        description: Git ref to deploy (SHA from a fork will work if a PR was issued on that SHA)
        required: false
        default: ""

jobs:
  deploy:
    permissions: 
      contents: read

    uses: ./.github/workflows/reusable-deploy-vercel.yml

    with:
      REF: ${{ inputs.REF || github.ref }}
    
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}