name: Preview Deployment

on: workflow_dispatch

jobs:
  deploy:
    permissions: 
      contents: read

    uses: ./.github/workflows/reusable-deploy-vercel.yml
    
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}