name: PROD Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions: 
      contents: read
      pull-requests: write

    uses: ./.github/workflows/reusable-deploy-vercel.yml

    with:
      PROD: true
    
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
